export const COMMANDS_RATE_LIMIT = 5000;

export const ROLE_SELECT_BUTTON_RATE_LIMIT = 10000;

export const UPDATE_BIO_BUTTON_RATE_LIMIT = 5000;
export const UPDATE_BIO_MODAL_RATE_LIMIT = 1000;

export const VIEW_MY_ORDERS_BUTTON_RATE_LIMIT = 1000;
export const CREATE_ORDER_BUTTON_RATE_LIMIT = 5000;

export const VIEW_ORDERS_BUTTON_RATE_LIMIT = 2000;

export const ORDER_DONE_BUTTON_RATE_LIMIT = 5000;
